<div class="row">
    <div class="col-md-12">
        <form role="form" id="usuario_form">
            <input type="hidden" class="form-control" id="usuario_id" name="usuario_id">
            <div class="form-group">
                <label>Rol</label>
                <select class="form-control" id="rol_id" name="rol_id">
                    <option value="">selecciona un rol</option>
                </select>
                <label>Nombre</label>
                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
                <label>Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="password">
            </div>
        </form>
    </div>
</div>