<tr>
    <td><?php echo $this->usuario->getRol()->getDescripcion(); ?></td>
    <td><?php echo $this->usuario->getNombre(); ?></td>
    <td><?php echo $this->usuario->getPassword(); ?></td>
    <td>
        <button type="button" class="btn btn-sm btn-default" onClick="edit(<?php echo $this->usuario->getId(); ?>);">
            <span class="glyphicon glyphicon-edit"></span>
        </button>
        <?php
        $session = Zend_Auth::getInstance()->getIdentity();
        if ($this->usuario->getId() != $session->id) {
            ?>
            <button type="button" class="btn btn-sm btn-danger" onClick="borrar(<?php echo $this->usuario->getId(); ?>);">
                <span class="glyphicon glyphicon-remove"></span>
            </button>
            <?php
        }
        ?>
    </td>
</tr>