<div class="row">
    <h3 class="text-center"><?php echo $this->viaje->getNombre(); ?></h3>
    <p>
        Este viaje esta programado para iniciar el <?php echo date('d-m-Y', strtotime($this->viaje->getFechaSalida())); ?>
        a las <?php echo date("g:i a", STRTOTIME($this->viaje->getHoraSalida())); ?>
        y finalizar el <?php echo date('d-m-Y', strtotime($this->viaje->getFechaRegreso())); ?>
        a las <?php echo date("g:i a", STRTOTIME($this->viaje->getHoraRegreso())); ?>
    </p>
    <br>
    <p>
        Los guias son
    </p>
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Categoria</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->guias as $g) { ?>
                <tr>
                    <td><?php echo $g->getCliente()->getPrimerNombre(); ?></td>
                    <td><?php echo $g->getCliente()->getPrimerApellido(); ?></td>
                    <td><?php echo $g->getCategoria()->getNombre(); ?></td>
                </tr>
                <?php
            }
            ?>
        </tbody>
    </table>
    <p>
        Los clientes inscritos al viaje son
    </p>
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>DPI</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->clientes as $c) { ?>
                <tr>
                    <td><?php echo $c->getPrimerNombre(); ?></td>
                    <td><?php echo $c->getPrimerApellido(); ?></td>
                    <td><?php echo $c->getDpi(); ?></td>
                </tr>
                <?php
            }
            ?>
        </tbody>
    </table>
    <p>
        Se visitaran los siguientes destinos
    </p>
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Pais</th>
                <th>Departamento</th>
                <th>Municipio</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->destinos as $d) { ?>
                <tr>
                    <td><?php echo $d->getNombre(); ?></td>
                    <td><?php echo $d->getPais()->getNombre(); ?></td>
                    <td><?php echo $d->getDepartamento()->getNombre(); ?></td>
                    <td><?php echo $d->getMunicipio()->getNombre(); ?></td>
                </tr>
                <?php
            }
            ?>
        </tbody>
    </table>
    <p>
        Se realizaran las siguientes actividades y se pueden obtener los siguientes logros
    </p>
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Actividad</th>
                <th>Logros</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->actividades_logros as $al) { ?>
                <tr>
                    <td><?php echo $al['actividad']->getNombre(); ?></td>
                    <td><?php echo $al['logros'] ?></td>
                </tr>
                <?php
            }
            ?>
        </tbody>
    </table>
</div>
