<div class="row">
    <form role="form" id="viaje_form">
        <div class="col-md-4">
            <input type="hidden" class="form-control" id="viaje_id" name="viaje_id">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
                <label>Fecha Salida</label>
                <input type="text" class="form-control" id="fecha_salida" name="fecha_salida" placeholder="dd-mm-aaaa">
                <label>Hora Salida</label>
                <input type="time" class="form-control" id="hora_salida" name="hora_salida" value="06:00">
                <label>Fecha Regreso</label>
                <input type="text" class="form-control" id="fecha_regreso" name="fecha_regreso" placeholder="dd-mm-aaaa">
                <label>Hora Regreso</label>
                <input type="time" class="form-control" id="hora_regreso" name="hora_regreso" value="18:00">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label>Destinos que se visitaran en el viaje</label>
                <div id="destinos">
                    <?php echo $this->destinos; ?>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label>Actividades que se realizaran en el viaje</label>
                <div id="actividades">
                    <?php echo $this->actividades; ?>
                </div>
            </div>
        </div>
    </form>
</div>