<form role="form" id="viaje_form">
    <div class="row" id="viaje_page">
        <div class="row">
            <ol class="breadcrumb">
                <li class="active">Viaje</li>
                <li><a onClick="mostrarPagina('destino_page');">Destinos</a></li>
                <li><a onClick="mostrarPagina('actividad_page');">Actividades</a></li>
                <li><a onClick="mostrarPagina('guia_page');">Guias</a></li>
                <li><a onClick="mostrarPagina('guardar_page');">Guardar</a></li>
            </ol>
        </div>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <input type="hidden" class="form-control" id="viaje_id" name="viaje_id" value="<?php echo $this->viajeId; ?>">
                <div class="form-group">
                    <label>Nombre</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
                    <label>Fecha Salida</label>
                    <input type="text" class="form-control" id="fecha_salida" name="fecha_salida" placeholder="dd-mm-aaaa">
                    <label>Hora Salida</label>
                    <input type="time" class="form-control" id="hora_salida" name="hora_salida" value="06:00">
                    <label>Fecha Regreso</label>
                    <input type="text" class="form-control" id="fecha_regreso" name="fecha_regreso" placeholder="dd-mm-aaaa">
                    <label>Hora Regreso</label>
                    <input type="time" class="form-control" id="hora_regreso" name="hora_regreso" value="18:00">
                </div>
                <div class="text-center">
                    <button type="button" class="btn btn-primary" onClick="mostrarPagina('destino_page');">Siguiente</button>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
    <div class="row" id="destino_page" style="display:none;">
        <div class="row">
            <ol class="breadcrumb">
                <li><a onClick="mostrarPagina('viaje_page');">Viaje</a></li>
                <li class="active">Destinos</li>
                <li><a onClick="mostrarPagina('actividad_page');">Actividades</a></li>
                <li><a onClick="mostrarPagina('guia_page');">Guias</a></li>
                <li><a onClick="mostrarPagina('guardar_page');">Guardar</a></li>
            </ol>
        </div>
        <div class="row">
            <div class="col-md-9">
                Selecciona los destinos que se visitaran en este viaje y luego presiona <span class="glyphicon glyphicon-arrow-right"></span>
            </div>
            <div class="col-md-3">
                <button type="button" class="btn btn-primary" onClick="terminarSeleccionDestino();">
                    Siguiente
                    <span class="glyphicon glyphicon-arrow-right"></span>
                </button>
            </div>
        </div>
        <div class="row">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Pais</th>
                        <th>Departamento</th>
                        <th>Municipio</th>
                        <th>Nombre</th>
                        <th>Descripcion</th>
                        <th>Seleccionar</th>
                    </tr>
                </thead>
                <tbody id="lista_destino">
                    <?php echo $this->destinos; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row" id="actividad_page" style="display:none;">
        <div class="row">
            <ol class="breadcrumb">
                <li><a onClick="mostrarPagina('viaje_page');">Viaje</a></li>
                <li><a onClick="mostrarPagina('destino_page');">Destinos</a></li>
                <li class="active">Actividades</li>
                <li><a onClick="mostrarPagina('guia_page');">Guias</a></li>
                <li><a onClick="mostrarPagina('guardar_page');">Guardar</a></li>
            </ol>
        </div>
        <div class="row">
            <div class="col-md-9">
                Selecciona las actividades que se realizaran en este viaje y luego presiona <span class="glyphicon glyphicon-arrow-right"></span>
            </div>
            <div class="col-md-3">
                <button type="button" class="btn btn-primary" onClick="terminarSeleccionActividad();">
                    Siguiente
                    <span class="glyphicon glyphicon-arrow-right"></span>
                </button>
            </div>
        </div>
        <div class="row">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Descripcion</th>
                        <th>Seleccionar</th>
                    </tr>
                </thead>
                <tbody id="lista_actividad">
                    <?php echo $this->actividades; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row" id="guia_page" style="display:none;">
        <div class="row">
            <ol class="breadcrumb">
                <li><a onClick="mostrarPagina('viaje_page');">Viaje</a></li>
                <li><a onClick="mostrarPagina('destino_page');">Destinos</a></li>
                <li><a onClick="mostrarPagina('actividad_page');">Actividades</a></li>
                <li class="active">Guias</li>
                <li><a onClick="mostrarPagina('guardar_page');">Guardar</a></li>
            </ol>
        </div>
        <div class="row">
            <div class="col-md-9">
                Selecciona a los guias para este viaje y luego presiona <span class="glyphicon glyphicon-arrow-right"></span>
            </div>
            <div class="col-md-3">
                <button type="button" class="btn btn-primary" onClick="terminarSeleccionGuia();">
                    Siguiente
                    <span class="glyphicon glyphicon-arrow-right"></span>
                </button>
            </div>
        </div>
        <div class="row">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nombre Cliente</th>
                        <th>Apellido Cliente</th>
                        <th>Categoria</th>
                        <th>Seleccionar</th>
                    </tr>
                </thead>
                <tbody id="lista_guia">
                    <?php echo $this->guias; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row" id="guardar_page" style="display:none;">
        <div class="row">
            <ol class="breadcrumb">
                <li><a onClick="mostrarPagina('viaje_page');">Viaje</a></li>
                <li><a onClick="mostrarPagina('destino_page');">Destinos</a></li>
                <li><a onClick="mostrarPagina('actividad_page');">Actividades</a></li>
                <li><a onClick="mostrarPagina('guia_page');">Guias</a></li>
                <li class="active">Guardar</li>
            </ol>
        </div>
        <div class="row well">
            <div class="col-md-12">
                <div class="alert alert-warning" id="no_viaje_alert" style="display:none;">
                    No has completado los datos del viaje.
                </div>
                <div class="alert alert-warning" id="no_destino_alert" style="display:none;">
                    No has seleccionado destinos.
                </div>
                <div class="alert alert-warning" id="no_actividad_alert" style="display:none;">
                    No has seleccionado actividades.
                </div>
                <div class="alert alert-warning" id="no_guia_alert" style="display:none;">
                    No has seleccionado un guia para el viaje.
                </div>
                <h3>Por favor verifica la informacion</h3>
                El viaje <strong id="informacion_viaje_nombre"></strong> se realizara desde el
                <strong id="informacion_viaje_salida"></strong> hasta el
                <strong id="informacion_viaje_regreso"></strong>
                <br>se visitaran los siguientes destinos
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Pais</th>
                            <th>Departamento</th>
                            <th>Municipio</th>
                            <th>Nombre</th>
                            <th>Descripcion</th>
                            <th>Seleccionar</th>
                        </tr>
                    </thead>
                    <tbody id="lista_destino_final">
                    </tbody>
                </table>
                <br>se realizaran las siguientes actividades
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Descripcion</th>
                            <th>Seleccionar</th>
                        </tr>
                    </thead>
                    <tbody id="lista_actividad_final">
                    </tbody>
                </table>
                <br>y el viaje sera guiado por
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nombre Cliente</th>
                            <th>Apellido Cliente</th>
                            <th>Categoria</th>
                            <th>Seleccionar</th>
                        </tr>
                    </thead>
                    <tbody id="lista_guia_final">
                    </tbody>
                </table>
                <div class="text-center">
                    <button type="button" class="btn btn-primary" onClick="guardar();" id="guardar_viaje_button" style="display:none;">Guardar Viaje</button>
                </div>
            </div>
        </div>
    </div>
</form>