<div class="row">
    <div class="col-md-12">
        <form role="form" id="viaje_form">
            <input type="hidden" class="form-control" id="viaje_id" name="viaje_id">
            <div class="form-group">
                <label>Fecha Salida</label>
                <input type="text" class="form-control" id="fecha_salida" name="fecha_salida" placeholder="25-01-1990">
                <label>Hora Salida</label>
                <input type="time" class="form-control" id="hora_salida" name="hora_salida" value="06:00">
                <label>Fecha Regreso</label>
                <input type="text" class="form-control" id="fecha_regreso" name="fecha_regreso" placeholder="25-01-1990">
                <label>Hora Regreso</label>
                <input type="time" class="form-control" id="hora_regreso" name="hora_regreso" value="18:00">
                <label>Destinos que se visitaran en el viaje</label>
                <div id="destinos">
                    <?php echo $this->destinos; ?>
                </div>
                <label>Actividades que se realizaran en el viaje</label>
                <div id="actividades">
                    <?php echo $this->actividades; ?>
                </div>
            </div>
        </form>
    </div>
</div>