<tr <?php echo ($this->viaje->getTerminado() == 1) ? 'class="alert-success"' : ''; ?>>
    <td class="al"><?php echo $this->viaje->getNombre(); ?></td>
    <td><?php echo date('d-m-Y', strtotime($this->viaje->getFechaSalida())); ?></td>
    <td><?php echo date("g:i a", STRTOTIME($this->viaje->getHoraSalida())); ?></td>
    <td><?php echo date('d-m-Y', strtotime($this->viaje->getFechaRegreso())); ?></td>
    <td><?php echo date("g:i a", STRTOTIME($this->viaje->getHoraRegreso())); ?></td>
    <td>
        <button type="button" class="btn btn-sm btn-info" onClick="lista(<?php echo $this->viaje->getId(); ?>);">
            <span class="glyphicon glyphicon-list"></span>
        </button>
        <?php
        if ($this->viaje->getTerminado() != 1) {
            ?>
            <button type="button" class="btn btn-sm btn-default" onClick="editV(<?php echo $this->viaje->getId(); ?>);">
                <span class="glyphicon glyphicon-edit"></span>
            </button>
            <button type="button" class="btn btn-sm btn-danger" onClick="borrar(<?php echo $this->viaje->getId(); ?>);">
                <span class="glyphicon glyphicon-remove"></span>
            </button>
            <?php
        }
        if ($this->viaje->getTerminado() != 1 &&
                strtotime(date('Y-m-d H:i:s')) > strtotime($this->viaje->getFechaRegreso() . ' ' . $this->viaje->getHoraRegreso())) {
            ?>
            <button type="button" class="btn btn-sm btn-primary" onClick="terminar(<?php echo $this->viaje->getId(); ?>);">
                <span class="glyphicon glyphicon-arrow-right"></span>
            </button>
        <?php } ?>
    </td>
</tr>