<tr>
    <td><?php echo $this->viaje->getNombre(); ?></td>
    <td><?php echo date('d-m-Y', strtotime($this->viaje->getFechaSalida())); ?></td>
    <td><?php echo date("g:i a", STRTOTIME($this->viaje->getHoraSalida())); ?></td>
    <td><?php echo date('d-m-Y', strtotime($this->viaje->getFechaRegreso())); ?></td>
    <td><?php echo date("g:i a", STRTOTIME($this->viaje->getHoraRegreso())); ?></td>
    <td>
        <button type="button" class="btn btn-sm btn-primary" onClick="seleccionarViaje(<?php echo $this->viaje->getId(); ?>);">
            <span class="glyphicon glyphicon-arrow-right"></span>
        </button>
    </td>
</tr>