<div class="row">
    <div class="alert alert-danger" id="error-alert" style="display:none;"></div>
    <div class="alert alert-success" id="success-alert" style="display:none;">
        <strong>El viaje se ha creado con exito.</strong>
    </div>
</div>
<?php echo $this->formulario; ?>
<div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2" style="text-align:center;">
        <button type="button" class="btn btn-primary" onClick="guardar();">Guardar Viaje</button>
    </div>
    <div class="col-md-5"></div>
</div>
<?php
echo $this->render('partials/checkbox.phtml');
$this->headScript()->appendFile('/js/viaje/init.js');
$this->headScript()->appendFile('/js/formulario.js');
$this->headScript()->appendFile('/js/nuevo.js');
?>