<div class="row">
    <ul class="nav nav-tabs" id="clientes_tab">
        <li class="active"><a href="#todos">Todos</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="todos">
            <div class="row" id="main_grid"></div>
        </div>
    </div>
</div>
<script id="all_template" type="text/x-kendo-template">
    <a class="k-button" href="\#" onclick="exportAll();">Exportar</a>
</script>
<?php
$this->headScript()->captureStart();
echo "var data = " . $this->data . ";";
$this->headScript()->captureEnd();
$this->headScript()->appendFile('/js/reporte/comun.js');
$this->headScript()->appendFile('/js/reporte/clientes.js');
?>