<div class="row">
    <ul class="nav nav-tabs" id="cuentas_tab">
        <li class="active"><a href="#todos">Todas</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="todos">
            <div class="row" id="main_grid"></div>
            <div class="row">
                <div class="col-md-11"></div>
                <div class="col-md-1">
                    <button type="button" class="btn btn-primary" onClick="exportAll();">Exportar</button>
                </div>
            </div>

        </div>
    </div>
</div>
<?php
$this->headScript()->captureStart();
echo "var data = " . $this->data . ";";
$this->headScript()->captureEnd();
$this->headScript()->appendFile('/js/reporte/cuentas.js');
?>