<div class="row">
    <h3>Aqui puedes encontrar la respuesta a las siguientes preguntas:</h3>
    <ul class="list-group">
        <li class="list-group-item"><a href="">¿Qué clientes se han inscrito a un viaje? o ¿Qué clientes asistieron a un viaje?</a></li>
        <li class="list-group-item"><a href="">¿Qué viajes ha realizado un cliente?</a></li>
        <li class="list-group-item"><a href="">¿Qué equipo ha alquilado un cliente?</a></li>
        <li class="list-group-item"><a href="">¿Cuantas veces se ha alquilado un equipo?</a></li>
        <li class="list-group-item"><a href="">¿Cuantos clientes tuvimos en algun año?</a></li>
        <li class="list-group-item"><a href="">¿Cuantos clientes han participado en una actividad?</a></li>
        <li class="list-group-item"><a href="">¿Cuales clientes han realizado una actividad?</a></li>
        <li class="list-group-item"><a href="">¿Cuales actividades ha realizado un cliente?</a></li>
    </ul>
</div>