<link href="<?php echo $this->baseUrl('css/login.css') ?>" rel="stylesheet">
<div class="container" align="center">
    <img src="/img/header_maintwo.jpg" alt="Kashem" class="img-rounded">
</div>
<div class="form-signin">
    <div class="alert alert-danger" id="login_form_alert" style="display:none;"></div>
    <input type="text" class="form-control" id="login_username" name="login_username" placeholder="Username" autofocus>
    <input type="password" class="form-control" id="login_password" name="login_password" placeholder="Password">
    <button class="btn btn-lg btn-primary btn-block" onClick="login();">Entrar</button>
</div>
<?php $this->headScript()->appendFile('/js/login.js');
?>