<div class="row">
    <div class="col-md-12">
        <form role="form" id="categoria_form">
            <input type="hidden" class="form-control" id="categoria_id" name="categoria_id">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
                <label>Descripcion</label>
                <textarea class="form-control" id="descripcion" name="descripcion" rows="3"></textarea>
            </div>
        </form>
    </div>
</div>