<div class="row">
    <div class="alert alert-danger" id="error-alert" style="display:none;"></div>
    <div class="alert alert-success" id="success-alert" style="display:none;">
        <strong>El alquiler se ha realizado con exito.</strong>
    </div>
</div>
<div class="row">
    <form class="form-horizontal" role="form" id="alquiler_form_1">
        <div class="form-group">
            <div class="col-md-2">
                <input class="form-control" type="hidden" id="cliente_id" name="cliente_id">
                <label>Nombre Cliente</label>
                <input class="form-control" type="text" id="nombre_cliente" name="nombre_cliente" readOnly>
            </div>
            <div class="col-md-2">
                <label>DPI</label>
                <input class="form-control" type="text" id="dpi_cliente" name="dpi_cliente" readOnly>
            </div>
            <div class="col-md-2">
                <label>Equipo alquilado</label>
                <input class="form-control" type="text" id="equipo_seleccionado" name="equipo_seleccionado" value="0" readOnly>
            </div>
            <div class="col-md-6">
            </div>
        </div>
    </form>
</div>
<div class="row" id="cliente_page">
    <div class="row">
        <ol class="breadcrumb">
            <li class="active">Cliente</li>
            <li><a onClick="mostrarPagina('equipo_page');">Equipo</a></li>
            <li><a onClick="mostrarPagina('alquiler_page');">Alquiler</a></li>
        </ol>
    </div>
    <div class="row">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Primer Nombre</th>
                    <th>Primer Apellido</th>
                    <th>DPI</th>
                    <th>Seleccionar</th>
                </tr>
            </thead>
            <tbody id="lista_cliente">
                <?php echo $this->clientes; ?>
            </tbody>
        </table>
    </div>
</div>
<div class="row" id="equipo_page" style="display:none;">
    <div class="row">
        <ol class="breadcrumb">
            <li><a onClick="mostrarPagina('cliente_page');">Cliente</a></li>
            <li class="active">Equipo</li>
            <li><a onClick="mostrarPagina('alquiler_page');">Alquiler</a></li>
        </ol>
    </div>
    <div class="row">
        <div class="col-md-9">
            Selecciona el equipo que le alquilaras a este cliente y luego presiona <span class="glyphicon glyphicon-arrow-right"></span>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-primary" onClick="terminarSeleccionEquipo();">
                Siguiente
                <span class="glyphicon glyphicon-arrow-right"></span>
            </button>
        </div>
    </div>
    <div class="row">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Identificador</th>
                    <th>Descripcion</th>
                    <th>Disponible</th>
                    <th>Seleccionar</th>
                </tr>
            </thead>
            <tbody id="lista_equipo">
                <?php echo $this->equipos; ?>
            </tbody>
        </table>
    </div>
</div>
<div class="row" id="alquiler_page" style="display:none;">
    <div class="row">
        <ol class="breadcrumb">
            <li><a onClick="mostrarPagina('cliente_page');">Cliente</a></li>
            <li><a onClick="mostrarPagina('equipo_page');">Equipo</a></li>
            <li class="active">Alquiler</li>
        </ol>
    </div>
    <div class="row well">
        <div class="col-md-12">
            <div class="alert alert-warning" id="no_cliente_alert" style="display:none;">No has seleccionado un cliente.</div>
            <div class="alert alert-warning" id="no_equipo_alert" style="display:none;">No has seleccionado equipo para alquilar.</div>
            <h3>Por favor verifica y completa la informacion</h3>
            Al cliente <strong id="informacion_cliente_nombre"></strong> quien se identifica con DPI <strong id="informacion_cliente_dpi"></strong> le alquilaras el siguiente equipo<br>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Identificador</th>
                        <th>Descripcion</th>
                        <th>Disponible</th>
                        <th>Seleccionar</th>
                    </tr>
                </thead>
                <tbody id="lista_equipo_final">
                </tbody>
            </table>
            <label>desde</label>
            <input type="text" class="form-control" id="renta" name="renta" placeholder="dd-mm-aaaa">
            <label>hasta</label><input type="text" class="form-control" id="devolucion" name="devolucion" placeholder="dd-mm-aaaa">
            <label>por un costo de</label><input type="text" class="form-control" id="costo" name="costo" placeholder="100.50"> quetzales<br>
            <label>y dejando un deposito de</label><input type="text" class="form-control" id="deposito" name="deposito" placeholder="100.50"> quetzales<br><br>
            <label>Comentarios:</label>
            <textarea class="form-control" id="comentario" name="comentario" rows="3"></textarea>
        </div>
        <br>
        <div class="col-md-5"></div>
        <div class="col-md-2" style="text-align:center;">
            <button type="button" class="btn btn-primary" id="alquiler_guardar_button" onClick="guardar();">
                Guardar
            </button>
        </div>
        <div class="col-md-5"></div>
    </div>
</div>
<?php
$this->headScript()->appendFile('/js/alquiler/init.js');
?>