<tr>
    <td><?php echo $this->equipo->getNombre(); ?></td>
    <td><?php echo $this->equipo->getCantidadExistente(); ?></td>
    <td><?php echo $this->equipo->getDescripcion(); ?></td>
    <td>
        <button type="button" class="btn btn-sm btn-default" onClick="edit(<?php echo $this->equipo->getId(); ?>);">
            <span class="glyphicon glyphicon-edit"></span>
        </button>
        <button type="button" class="btn btn-sm btn-danger" onClick="borrar(<?php echo $this->equipo->getId(); ?>);">
            <span class="glyphicon glyphicon-remove"></span>
        </button>
    </td>
</tr>