<div class="row">
    <ul class="nav nav-tabs" id="cuentas_tab">
        <li class="active"><a href="#viaje_pendientes">De Viaje Pendientes</a></li>
        <li><a href="#alquiler_pendientes">De Alquiler Pendientes</a></li>
        <li><a href="#viaje_canceladas">De Viaje Canceladas</a></li>
        <li><a href="#alquiler_canceladas">De Alquiler Canceladas</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="viaje_pendientes">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Primer Nombre</th>
                        <th>Primer Apellido</th>
                        <th>Viaje</th>
                        <th>Fecha Salida</th>
                        <th>Hora Salida</th>
                        <th>Fecha Regreso</th>
                        <th>Hora Regreso</th>
                        <th>Tipo de Pago</th>
                        <th>Monto</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody id="lista_viaje_pendientes">
                    <?php echo $this->cuentas_viaje_pendientes; ?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="alquiler_pendientes">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Primer Nombre</th>
                        <th>Primer Apellido</th>
                        <th>Renta</th>
                        <th>Devolucion</th>
                        <th>Deposito</th>
                        <th>Tipo de Pago</th>
                        <th>Monto</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody id="lista_alquiler_pendientes">
                    <?php echo $this->cuentas_alquiler_pendientes; ?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="viaje_canceladas">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Primer Nombre</th>
                        <th>Primer Apellido</th>
                        <th>Viaje</th>
                        <th>Fecha Salida</th>
                        <th>Hora Salida</th>
                        <th>Fecha Regreso</th>
                        <th>Hora Regreso</th>
                        <th>Tipo de Pago</th>
                        <th>Monto</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody id="lista_viaje_canceladas">
                    <?php echo $this->cuentas_viaje_canceladas; ?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="alquiler_canceladas">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Primer Nombre</th>
                        <th>Primer Apellido</th>
                        <th>Renta</th>
                        <th>Devolucion</th>
                        <th>Deposito</th>
                        <th>Tipo de Pago</th>
                        <th>Monto</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody id="lista_alquiler_canceladas">
                    <?php echo $this->cuentas_alquiler_canceladas; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php
$this->headScript()->appendFile('/js/cuenta/init.js');
?>