<div class="row">
    <ul class="nav nav-tabs" id="cuenta_tipo_tab">
        <li class="active"><a href="#viaje_pendientes">Pendientes de Viaje</a></li>
        <li><a href="#alquiler_pendientes">Pendientes de Alquiler</a></li>
        <li><a href="#viaje_canceladas">Canceladas de Viaje</a></li>
        <li><a href="#alquiler_canceladas">Canceladas de Alquiler</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="viaje_pendientes">
        </div>
        <div class="tab-pane" id="alquiler_pendientes">
        </div>
        <div class="tab-pane" id="viaje_canceladas">
        </div>
        <div class="tab-pane" id="alquiler_canceladas">
        </div>
    </div>
</div>
<?php
$this->headScript()->appendFile('/js/cuenta/init.js');
?>