<tr>
    <td><?php echo $this->cuenta->getCliente()->getPrimerNombre(); ?></td>
    <td><?php echo $this->cuenta->getCliente()->getPrimerApellido(); ?></td>
    <td><?php echo $this->cuenta->getViaje()->getNombre(); ?></td>
    <td><?php echo date('d-m-Y', strtotime($this->cuenta->getViaje()->getFechaSalida())); ?></td>
    <td><?php echo date("g:i a", STRTOTIME($this->cuenta->getViaje()->getHoraSalida())); ?></td>
    <td><?php echo date('d-m-Y', strtotime($this->cuenta->getViaje()->getFechaRegreso())); ?></td>
    <td><?php echo date("g:i a", STRTOTIME($this->cuenta->getViaje()->getHoraRegreso())); ?></td>
    <td><?php echo $this->cuenta->getTipoPago()->getNombre(); ?></td>
    <td><?php echo $this->cuenta->getMonto(); ?></td>
    <td>
        <?php
        if ($this->cuenta->getEstado() == 'pendiente') {
            ?>
            <button type="button" class="btn btn-sm btn-default" onClick="iniciarCancelacion(<?php echo $this->cuenta->getId(); ?>);">
                Cancelar
                <span class="glyphicon glyphicon-arrow-right"></span>
            </button>
            <?php
        } else {
            ?>
            <button type="button" class="btn btn-sm btn-default" onClick="detalles(<?php echo $this->cuenta->getId(); ?>);">
                <span class="glyphicon glyphicon-info-sign"></span>
            </button>
            <?php
        }
        ?>
    </td>
</tr>