<tr>
    <td><?php echo $this->cuenta->getCliente()->getPrimerNombre(); ?></td>
    <td><?php echo $this->cuenta->getCliente()->getPrimerApellido(); ?></td>
    <td><?php echo date('d-m-Y', strtotime($this->cuenta->getAlquiler()->getRenta())); ?></td>
    <td><?php echo date('d-m-Y', strtotime($this->cuenta->getAlquiler()->getDevolucion())); ?></td>
    <td><?php echo $this->cuenta->getAlquiler()->getDeposito(); ?></td>
    <td><?php echo $this->cuenta->getTipoPago()->getNombre(); ?></td>
    <td><?php echo $this->cuenta->getMonto(); ?></td>
    <td>
        <?php
        if ($this->cuenta->getEstado() == 'pendiente') {
            ?>
            <button type="button" class="btn btn-sm btn-default" onClick="iniciarCancelacion(<?php echo $this->cuenta->getId(); ?>);">
                Cancelar
                <span class="glyphicon glyphicon-arrow-right"></span>
            </button>
            <?php
        } else {
            ?>
            <button type="button" class="btn btn-sm btn-default" onClick="detalles(<?php echo $this->cuenta->getId(); ?>);">
                <span class="glyphicon glyphicon-info-sign"></span>
            </button>
            <a href="/cuenta/imprimir?id=<?php echo $this->cuenta->getId(); ?>" target="_blank">
                <button type="button" class="btn btn-sm btn-default">
                    <span class="glyphicon glyphicon-print"></span>
                </button>
            </a>
            <?php
        }
        ?>
    </td>
</tr>