<h3 class="text-center">K'ashem</h3>
<table class="table table-bordered">
    <tbody>
        <tr>
            <td colspan="2">Guatemala, <?php echo date("d-m-Y H:i:s"); ?></td>
            <td colspan="1">Recibo por la cuenta #</td>
            <td colspan="1"><strong><?php echo $this->cuenta->getId(); ?></strong></td>
        </tr>
        <tr>
            <td colspan="1">Cliente</td>
            <td colspan="1"><strong><?php echo $this->cuenta->getCliente()->getPrimerNombre() . ' ' . $this->cuenta->getCliente()->getPrimerApellido(); ?></strong></td>
            <td colspan="1">Metodo de pago</td>
            <td colspan="1"><strong><?php echo $this->cuenta->getTipoPago()->getNombre(); ?></strong></td>
        </tr>
        <tr>
            <td colspan="3">
                Por alquiler de equipo
                <?php
                foreach ($this->equipos as $e) {
                    ?>
                    <br><strong><?php echo $e->getNombre() . ' ' . $e->getIdentificador(); ?></strong>
                    <?php
                }
                ?>
            </td>
            <td colspan="1"></td>
        </tr>
        <tr>
            <td colspan="3">Total</td>
            <td colspan="1"><strong>Q <?php echo $this->cuenta->getMonto(); ?></strong></td>
        </tr>
    </tbody>
</table>