<div class="row">
    <p>Cuenta No. <strong><?php echo $this->cuenta->getId(); ?></strong></p>
    <p>Cliente: <strong><?php echo $this->cuenta->getCliente()->getPrimerNombre() . ' ' . $this->cuenta->getCliente()->getPrimerApellido(); ?></strong></p>
    <p>Detalle:</p>
    <p>
        Por asistir al viaje
        <strong><?php echo $this->cuenta->getViaje()->getNombre(); ?></strong>
        que se realizo del
        <strong><?php echo date('d-m-Y', strtotime($this->cuenta->getViaje()->getFechaSalida())); ?></strong>
        al
        <strong><?php echo date('d-m-Y', strtotime($this->cuenta->getViaje()->getFechaRegreso())); ?></strong>
        con un costo de
    </p>
    <p class="text-right">Q <?php echo $this->cuenta->getMonto(); ?></p>
</div>
<div class="row">
    <div class="col-md-4">
        <label>Metodo de pago:</label>
    </div>
    <div class = "col-md-4">
        <select class = "form-control" id = "tipo_de_pago_id" name = "tipo_de_pago_id" onChange="cambioTipoPago();">
            <?php echo $this->tipos_de_pago; ?>
        </select>
        <br>
    </div>
    <div class="col-md-4"></div>
</div>
<div class="row" id="numero_cheque_row" style="display:none">
    <div class="col-md-4">
        <label>Numero de cheque:</label>
    </div>
    <div class = "col-md-4">
        <input type="text" class = "form-control" id = "numero_cheque" name = "numero_cheque" value ="<?php echo $this->cuenta->getNumeroCheque(); ?>">
        <br>
    </div>
    <div class="col-md-4"></div>
</div>
<div class="row"  id="numero_tarjeta_row" style="display:none">
    <div class="col-md-4">
        <label>Numero de tarjeta:</label>
    </div>
    <div class="col-md-4">
        <input type="text" class = "form-control" id = "numero_tarjeta" name = "numero_tarjeta" value ="<?php echo $this->cuenta->getNumeroTarjeta(); ?>">
        <br>
    </div>
    <div class="col-md-4"></div>
</div>
<div class="row"  id="numero_autorizacion_row" style="display:none">
    <div class="col-md-4">
        <label>Numero de Autorizacion:</label>
    </div>
    <div class="col-md-4">
        <input type="text" class = "form-control" id = "numero_autorizacion" name = "numero_autorizacion" value ="<?php echo $this->cuenta->getNumeroAutorizacion(); ?>">
        <br>
    </div>
    <div class="col-md-4"></div>
</div>
<div class="row"  id="emisor_row" style="display:none">
    <div class="col-md-4">
        <label>Emisor:</label>
    </div>
    <div class="col-md-4">
        <input type="text" class = "form-control" id = "emisor" name = "emisor" value ="<?php echo $this->cuenta->getEmisor(); ?>">
        <br>
    </div>
    <div class="col-md-4"></div>
</div>
<div class="row"  id="banco_row" style="display:none">
    <div class="col-md-4">
        <label>Banco:</label>
    </div>
    <div class="col-md-4">
        <input type="text" class = "form-control" id = "banco" name = "banco" value ="<?php echo $this->cuenta->getBanco(); ?>">
        <br>
    </div>
    <div class="col-md-4"></div>
</div>