<div class="row">
    <form role="form" id="cliente_form">
        <div class="col-md-6">
            <div class="form-group">
                <input type="hidden" id="cliente_id" name="cliente_id">
                <label>Pais</label>
                <select class="form-control" id="pais_id" name="pais_id" onChange="cambioPais(this);">
                    <option value="">selecciona un pais</option>
                </select>
                <label>Departamento</label>
                <select class="form-control" id="departamento_id" name="departamento_id" onChange="cambioDepartamento(this);">
                    <option value="">selecciona un departamento</option>
                </select>
                <label>Municipio</label>
                <select class="form-control" id="municipio_id" name="municipio_id">
                    <option value="">selecciona un municipio</option>
                </select>
                <label>Primer Nombre</label>
                <input type="text" class="form-control" id="primer_nombre" name="primer_nombre" placeholder="Primer Nombre">
                <label>Segundo Nombre</label>
                <input type="text" class="form-control" id="segundo_nombre" name="segundo_nombre" placeholder="Segundo Nombre">
                <label>Primer Apellido</label>
                <input type="text" class="form-control" id="primer_apellido" name="primer_apellido" placeholder="Primer Apellido">
                <label>Segundo Apellido</label>
                <input type="text" class="form-control" id="segundo_apellido" name="segundo_apellido" placeholder="Segundo Apellido">
                <label>Fecha de Nacimiento</label>
                <input type="text" class="form-control" id="fecha_nacimiento" name="fecha_nacimiento" placeholder="25-01-1990">
                <label>Genero</label>
                <select class="form-control" id="genero" name="genero">
                    <option value="">selecciona un genero</option>
                    <option value="masculino">Masculino</option>
                    <option value="femenino">Femenino</option>
                </select>
                <label>DPI</label>
                <input type="text" class="form-control" id="dpi" name="dpi" placeholder="123456789">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>Telefono</label>
                <input type="text" class="form-control" id="telefono" name="telefono" placeholder="12345678">
                <label>Direccion</label>
                <input type="text" class="form-control" id="direccion" name="direccion" placeholder="">
                <label>Correo Electronico</label>
                <input type="text" class="form-control" id="correo_electronico" name="correo_electronico" placeholder="email@domain.com">
                <label>Usuario de Facebook</label>
                <input type="text" class="form-control" id="usuario_facebook" name="usuario_facebook" placeholder="">
                <label>Contacto de Emergencia</label>
                <input type="text" class="form-control" id="contacto_emergencia" name="contacto_emergencia" placeholder="">
                <label>Telefono de Emergencia</label>
                <input type="text" class="form-control" id="telefono_emergencia" name="telefono_emergencia" placeholder="">
                <label>Observaciones Medicas</label>
                <textarea class="form-control" id="observacion_medica" name="observacion_medica" rows="3"></textarea>
                <label>Observaciones Generales</label>
                <textarea class="form-control" id="observacion_general" name="observacion_general" rows="3"></textarea>
            </div>
        </div>
    </form>
</div>