<tr>
    <td><?php echo $this->cliente->getPrimerNombre(); ?></td>
    <td><?php echo $this->cliente->getPrimerApellido(); ?></td>
    <td>
        <button type="button" class="btn btn-sm btn-default" onClick="edit(<?php echo $this->cliente->getId(); ?>);">
            <span class="glyphicon glyphicon-edit"></span>
        </button>
        <button type="button" class="btn btn-sm btn-danger" onClick="borrar(<?php echo $this->cliente->getId(); ?>);">
            <span class="glyphicon glyphicon-remove"></span>
        </button>
    </td>
</tr>