<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>K'ashem :: admin</title>
        <link href="<?php echo $this->baseUrl('css/bootstrap.min.css') ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl('css/jquery-ui-1.10.3.custom.min.css') ?>" rel="stylesheet">
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/index">K'ashem</a>
                </div>
                <?php
                $session = Zend_Auth::getInstance()->getIdentity();
                if ($session != null) {
                    ?>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Nuevo<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/actividad/nueva">Actividad</a></li>
                                    <li><a href="#">Alquiler</a></li>
                                    <li><a href="/categoria/nueva">Categoria Guia</a></li>
                                    <li><a href="/clientes/nuevo">Cliente</a></li>
                                    <li><a href="/departamento/nuevo">Departamento</a></li>
                                    <li><a href="#">Destino</a></li>
                                    <li><a href="/inventario/formulario">Equipo</a></li>
                                    <li><a href="#">Guia</a></li>
                                    <li><a href="#">Logro</a></li>
                                    <li><a href="/municipio/nuevo">Municipio</a></li>
                                    <li><a href="/pais/nuevo">Pais</a></li>
                                    <li><a href="#">Usuario</a></li>
                                    <li><a href="#">Viaje</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Lista<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/actividad">Actividad</a></li>
                                    <li><a href="#">Alquiler</a></li>
                                    <li><a href="/categoria">Categoria Guia</a></li>
                                    <li><a href="/clientes">Clientes</a></li>
                                    <li><a href="/departamento">Departamento</a></li>
                                    <li><a href="#">Destino</a></li>
                                    <li><a href="/inventario">Equipo</a></li>
                                    <li><a href="#">Guia</a></li>
                                    <li><a href="#">Logro</a></li>
                                    <li><a href="/municipio">Municipio</a></li>
                                    <li><a href="/pais">Pais</a></li>
                                    <li><a href="#">Usuario</a></li>
                                    <li><a href="#">Viaje</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a>
                                    <span class="glyphicon glyphicon-user"></span>
                                    <?php echo $session->nombre; ?>
                                </a>
                            </li>
                            <li>
                                <a onClick="logout();">
                                    Salir
                                </a>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                    <?php
                }
                ?>
            </div>
        </div>
        <!--Container-->
        <div class="container" style="margin-top:60px;">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript">
                                window.jQuery || document.write('<script src="<?php echo $this->baseUrl("js/jquery.min.js") ?>"><\/script>');
    </script>
    <script src="<?php echo $this->baseUrl('js/bootstrap.min.js') ?>"></script>
    <script src="<?php echo $this->baseUrl('js/jquery-ui-1.10.3.custom.min.js') ?>"></script>
    <!--jquery init-->
    <script type="text/javascript">
        function logout()
        {
            $.ajax(
                    "/auth/logout",
                    {
                        method: 'post',
                        success: function(response)
                        {
                            if (response.success)
                            {
                                window.location.assign('/login');
                            }
                        }
                    }
            );
        }
    </script>
    <?php echo $this->headScript(); ?>

</body>
</html>
