<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>K'ashem :: admin</title>
        <link href="<?php echo $this->baseUrl('css/bootstrap.min.css') ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl('css/jquery-ui-1.10.3.custom.min.css') ?>" rel="stylesheet">
    </head>
    <body>
        <div class="modal fade" id="delete-modal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="delete-modal-title">Eliminar</h4>
                    </div>
                    <div class="modal-body" id="delete-modal-body">
                        ¿Realmente quieres eliminar este elemento?
                    </div>
                    <div class="modal-footer" id="modal-footer">
                        <button type="button" class="btn btn-danger" id="delete-modal-si-button">Si</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/index">K'ashem</a>
                </div>
                <?php
                $session = Zend_Auth::getInstance()->getIdentity();
                if ($session != null) {
                    ?>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Ir a<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/actividad">Actividad</a></li>
                                    <li><a href="/categoria">Categoria Guia</a></li>
                                    <li><a href="/cliente">Clientes</a></li>
                                    <li><a href="/departamento">Departamento</a></li>
                                    <li><a href="/destino">Destino</a></li>
                                    <li><a href="/equipo">Equipo</a></li>
                                    <li><a href="/guia">Guia</a></li>
                                    <li><a href="/logro">Logro</a></li>
                                    <li><a href="/municipio">Municipio</a></li>
                                    <li><a href="/pais">Pais</a></li>
                                    <li><a href="/usuario">Usuario</a></li>
                                    <li><a href="/viaje">Viaje</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#" >Inscripciones</a>
                            </li>
                            <li>
                                <a href="#" >Alquiler</a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a>
                                    <span class="glyphicon glyphicon-user"></span>
                                    <?php echo $session->nombre; ?>
                                </a>
                            </li>
                            <li>
                                <a onClick="logout();">
                                    Salir
                                </a>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                    <?php
                }
                ?>
            </div>
        </div>
        <!--Container-->
        <?php
        if ($session != null) {
            ?>
            <div class="container" style="margin-top:60px;">
                <div class="col-md-2">
                    <ul class="list-group">
                        <li class="list-group-item"><a href="/actividad">Actividad</a></li>
                        <li class="list-group-item"><a href="/categoria">Categoria Guia</a></li>
                        <li class="list-group-item"><a href="/cliente">Cliente</a></li>
                        <li class="list-group-item"><a href="/departamento">Departamento</a></li>
                        <li class="list-group-item"><a href="/destino">Destino</a></li>
                        <li class="list-group-item"><a href="/equipo">Equipo</a></li>
                        <li class="list-group-item"><a href="/guia">Guia</a></li>
                        <li class="list-group-item"><a href="/logro">Logro</a></li>
                        <li class="list-group-item"><a href="/municipio">Municipio</a></li>
                        <li class="list-group-item"><a href="/pais">Pais</a></li>
                        <li class="list-group-item"><a href="/usuario">Usuario</a></li>
                        <li class="list-group-item"><a href="/viaje">Viaje</a></li>
                    </ul>
                </div>
                <div class="col-md-10">
                    <form class="form-horizontal" role="form" id="busqueda_form" style="display:none;">
                        <div class="form-group">
                            <div class="col-md-2">
                                <select class="form-control" id="campo_busqueda" name="campo_busqueda">
                                    <option value="">Campo</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <input class="form-control" type="text" id="valor_busqueda" name="valor_busqueda" placeholder="Valor">
                            </div>
                            <div class="col-md-2">
                                <button type="button" class="btn btn-primary" id="busqueda_button">
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                                <button type="button" class="btn btn-danger" onClick="location.reload();">
                                    <span class="glyphicon glyphicon-refresh"></span>
                                </button>
                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-md-2">
                                <!----
                                <button type="button" class="btn btn-default">
                                    <span class="glyphicon glyphicon-backward"></span>
                                </button>
                                <button type="button" class="btn btn-default">
                                    <span class="glyphicon glyphicon-forward"></span>
                                </button>
                                --->
                            </div>
                            <div class="col-md-2">
                                <a href="#" id="nuevo_link">
                                    <button type="button" class="btn btn-success">
                                        <span class="glyphicon glyphicon-plus"></span>
                                    </button>
                                </a>
                            </div>
                        </div>
                    </form>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
            <?php
        } else {
            ?>
            <div class="container" style="margin-top:60px;">
                <?php echo $this->layout()->content; ?>
            </div>
            <?php
        }
        ?>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript">
                                    window.jQuery || document.write('<script src="<?php echo $this->baseUrl("js/jquery.min.js") ?>"><\/script>');
        </script>
        <script src="<?php echo $this->baseUrl('js/bootstrap.min.js') ?>"></script>
        <script src="<?php echo $this->baseUrl('js/jquery-ui-1.10.3.custom.min.js') ?>"></script>
        <!--jquery init-->
        <script type="text/javascript">
            function logout()
            {
                $.ajax(
                        "/auth/logout",
                        {
                            method: 'post',
                            success: function(response)
                            {
                                if (response.success)
                                {
                                    window.location.assign('/login');
                                }
                            }
                        }
                );
            }
        </script>
        <?php echo $this->headScript(); ?>

    </body>
</html>
