<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <form role="form">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
                <label>Descripcion</label>
                <textarea class="form-control" id="descripcion" name="descripcion" rows="3"></textarea>
            </div>
            <button type="button" class="btn btn-primary">Guardar</button>
        </form>
    </div>
    <div class="col-md-4"></div>
</div>