<tr>
    <td><?php echo $this->actividad->getNombre(); ?></td>
    <td><?php echo $this->actividad->getDescripcion(); ?></td>
    <td>
        <button type="button" class="btn btn-sm btn-default" onClick="edit(<?php echo $this->actividad->getId(); ?>);">
            <span class="glyphicon glyphicon-edit"></span>
        </button>
        <button type="button" class="btn btn-sm btn-danger" onClick="borrar(<?php echo $this->actividad->getId(); ?>);">
            <span class="glyphicon glyphicon-remove"></span>
        </button>
    </td>
</tr>