<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <form role="form">
            <div class="form-group">
                <label>Primer Nombre</label>
                <input type="text" class="form-control" id="primer_nombre" name="primer_nombre" placeholder="Primer Nombre">
                <label>Segundo Nombre</label>
                <input type="text" class="form-control" id="segundo_nombre" name="segundo_nombre" placeholder="Segundo Nombre">
                <label>Primer Apellido</label>
                <input type="text" class="form-control" id="primer_apellido" name="primer_apellido" placeholder="Primer Apellido">
                <label>Segundo Apellido</label>
                <input type="text" class="form-control" id="segundo_apellido" name="segundo_apellido" placeholder="Segundo Apellido">
                <label>DPI</label>
                <input type="text" class="form-control" id="dpi" name="dpi" placeholder="123456789">
                <label>Genero</label>
                <select class="form-control" id="genero" name="genero">
                    <option>Masculino</option>
                    <option>Femenino</option>
                </select>
                <label>Fecha de Nacimiento</label>
                <input type="text" class="form-control" id="" name="" placeholder="01/01/1990">
                <label>Nacionalidad</label>
                <input type="text" class="form-control" id="" name="" placeholder="Guatemalteco">
                <label>Correo Electronico</label>
                <input type="text" class="form-control" id="" name="" placeholder="email@domain.com">
                <label>Usuario de Facebook</label>
                <input type="text" class="form-control" id="" name="" placeholder="">
                <label>Telefono</label>
                <input type="text" class="form-control" id="" name="" placeholder="12345678">
                <label>Contacto de Emergencia</label>
                <input type="text" class="form-control" id="" name="" placeholder="">
                <label>Telefono de Emergencia</label>
                <input type="text" class="form-control" id="" name="" placeholder="">
                <label>Direccion</label>
                <input type="text" class="form-control" id="" name="" placeholder="">
                <label>Municipio</label>
                <select class="form-control" id="municipio" name="municipio">


                </select>
                <label>Departamento</label>
                <select class="form-control" id="departamento" name="departamento">

                </select>
                <label>Observaciones Medicas</label>
                <textarea class="form-control" id="observaciones_medicas" name="observaciones_medicas" rows="3"></textarea>
                <label>Observaciones Generales</label>
                <textarea class="form-control" id="observaciones_generales" name="observaciones_generales" rows="3"></textarea>
            </div>
            <button type="button" class="btn btn-primary">Guardar</button>
        </form>
    </div>
    <div class="col-md-4"></div>
</div>