<div class="modal fade" id="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modal-title">Cliente xyz</h4>
            </div>
            <div class="modal-body" id="modal-body">
                <?php echo $this->formulario; ?>
            </div>
            <div class="modal-footer" id="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Primer Nombre</th>
            <th>Primer Apellido</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        <?php echo $this->clientes; ?>
    </tbody>
</table>
<?php
$this->headScript()->appendFile('/js/cliente/index.js');
$this->headScript()->appendFile('/js/cliente/formulario.js');
?>