<div class="row">
    <div class="alert alert-danger" id="error-alert" style="display:none;"></div>
    <div class="alert alert-success" id="success-alert" style="display:none;">
        <strong>El cliente se ha creado con exito.</strong>
    </div>
</div>
<?php echo $this->formulario; ?>
<div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2" style="text-align:center;">
        <button type="button" class="btn btn-primary" onClick="guardar();">Guardar Cliente</button>
    </div>
    <div class="col-md-5"></div>
</div>
<?php
$this->headScript()->appendFile('/js/cliente/formulario.js');
$this->headScript()->appendFile('/js/cliente/nuevo.js');
?>