INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (1,1,'alta verapaz');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (2,1,'baja verapaz');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (3,1,'chimaltenango');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (4,1,'chiquimula');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (5,1,'el progreso');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (6,1,'escuintla');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (7,1,'guatemala');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (8,1,'huehuetenango');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (9,1,'izabal');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (10,1,'jalapa');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (11,1,'jutiapa');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (12,1,'peten');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (13,1,'quetzaltenango');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (14,1,'quiche');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (15,1,'retalhuleu');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (16,1,'sacatepequez');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (17,1,'san marcos');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (18,1,'santa rosa');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (19,1,'solola');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (20,1,'suchitepequez');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (21,1,'totonicapan');
INSERT INTO `departamento`(`id`,`pais_id`,`nombre`) VALUES (22,1,'zacapa');