INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'fray bartolome de las casas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'coban');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'chahal');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'san pedro carcha');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'cahabon');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'lanquin');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'senahu');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'panzos');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'san cristobal verapaz');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'san juan chamelco');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'santa cruz verapaz');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'tucuru');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'tamahu');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'tactic');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'santa catarina la tinta');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'raxruja');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (1,'chisec');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (2,'cubulco');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (2,'purulha');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (2,'san miguel chicaj');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (2,'rabinal');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (2,'salama');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (2,'san jeronimo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (2,'el chol');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (2,'granados');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'tecpan guatemala');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'san martin jilotepeque');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'san jose poaquil');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'santa apolonia');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'comalapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'chimaltenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'zaragoza');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'el tejar');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'patzun');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'santa cruz balanya');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'patzicia');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'san andres itzapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'parramos');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'pochuta');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'acatenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (3,'yepocapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (4,'camotan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (4,'jocotan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (4,'chiquimula');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (4,'esquipulas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (4,'san juan la ermita');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (4,'san jose la arada');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (4,'olopa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (4,'san jacinto');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (4,'quetzaltepeque');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (4,'ipala');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (4,'concepcion las minas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (5,'san agustin acasaguastlan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (5,'morazan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (5,'san cristobal acasguastlan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (5,'el jicaro');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (5,'guastatoya');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (5,'sanarate');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (5,'san antonio la paz');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (5,'sansare');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'escuintla');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'siquinala');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'palin');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'santa lucia cotzulmalguapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'san vicente pacaya');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'tiquisate');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'nueva concepcion');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'guanagazapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'la democracia');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'masagua');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'la gomera');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'san jose');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (6,'iztapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'chuarrancho');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'san raymundo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'san juan sacatepequez');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'san jose del golfo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'san pedro ayampuc');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'chinautla');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'palencia');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'san pedro sacatepequez');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'guatemala');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'mixco');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'san jose pinula');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'santa catarina pinula');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'villa nueva');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'villa canales');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'fraijanes');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'petapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (7,'amatitlan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'barillas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'san mateo ixtatan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'nenton');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'san sebastian coatan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'santa eulalia');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'jacaltenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'santa ana huista');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'san miguel acatan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'san rafael la independencia');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'san antonio huista');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'soloma');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'la democracia');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'san juan ixcoy');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'chiantla');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'la libertad');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'cuilco');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'aguacatan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'san juan atitan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'san idelfonso ixtahuacan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'san sebastian huehuetenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'colotenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'san rafael petzal');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'tectitan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'san gaspar ixchil');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'santa barbara');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'huehuetenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'malacatancito');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'union cantinil');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'concepcion huista');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'santiago chimaltenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'san pedro necta');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (8,'todos santos cuchumatan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (9,'puerto barrios');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (9,'livingston');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (9,'el estor');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (9,'morales');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (9,'los amates');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (10,'san pedro pinula');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (10,'jalapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (10,'san luis jilotepeque');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (10,'mataquescuintla');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (10,'san manuel chaparron');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (10,'monjas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (10,'san carlos alzatate');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'agua blanca');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'santa catarina mita');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'el progreso');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'jutiapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'asuncion mita');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'quesada');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'san jose acatempa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'yupiltepeque');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'jalpatagua');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'atescatempa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'comapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'el adelanto');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'zapotitlan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'jerez');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'conguaco');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'moyuta');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (11,'pasaco');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (12,'melchor de mencos');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (12,'flores');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (12,'san jose');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (12,'san andres');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (12,'la libertad');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (12,'san benito');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (12,'santa ana');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (12,'dolores');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (12,'san francisco');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (12,'sayaxche');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (12,'poptun');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (12,'san luis');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'san carlos sija');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'cabrican');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'huitan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'sibilia');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'palestina de los altos');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'cajola');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'san francisco la union');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'san juan ostuncalco');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'san miguel siguila');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'olintepeque');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'la esperanza');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'salcaja');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'quetzaltenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'san mateo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'concepcion chiquirichapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'cantel');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'san martin sacatepequez');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'colomba');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'almolonga');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'zunil');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'el palmar');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'coatepeque');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'flores costa cuca');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (13,'genova');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'ixcan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'nebaj');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'chajul');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'uspantan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'chicaman');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'san juan cotzal');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'cunen');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'san andres sajcabaja');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'sacapulas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'canilla');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'san pedro jocopilas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'san bartolome jocotenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'zacualpa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'san antonio ilotenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'santa cruz del quiche');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'joyabaj');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'chinique');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'chiche');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'patzite');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'chichicastenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (14,'pachalum');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (15,'nuevo san carlos');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (15,'san felipe retalhuleu');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (15,'el asintal');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (15,'san andres villa seca');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (15,'san martin zapotitlan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (15,'santa cruz mulua');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (15,'san sebastian');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (15,'retalhuleu');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (15,'champerico');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'sumpango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'santo domingo xenacoj');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'santiago sacatepequez');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'pastores');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'san lucas sacatepequez');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'san bartolome milpas altas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'antigua guatemala');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'jocotenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'santa lucia milpas altas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'santa catarina barahona');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'san antonio aguas calientes');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'san miguel dueñas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'magdalena milpas altas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'ciudad vieja');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'santa maria de jesus');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (16,'alotenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'tacana');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'concepcion tutuapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'san miguel ixtahuacan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'san jose ojetenam');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'sipacapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'tejutla');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'comitancillo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'ixchiguan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'sibinal');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'tajumulco');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'rio blanco');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'san marcos');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'san lorenzo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'san pablo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'malacatan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'san pedro sacatepequez');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'san antonio sacatepequez');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'san rafael pie de la cuesta');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'esquipulas palo gordo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'el rodeo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'san cristobal cucho');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'el tumbador');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'nuevo progreso');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'catarina');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'la reforma');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'el quetzal');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'pajapita');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'ayutla');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (17,'ocos');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'santa rosa de lima');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'san rafael las flores');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'casillas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'nueva santa rosa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'santa cruz naranjo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'barberena');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'cuilapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'pueblo nuevo viñas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'oratorio');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'santa maria ixhuatan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'taxisco');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'chiquimulilla');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'guazacapan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (18,'san juan tecuaco');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'solola');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'nahuala');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'santa catarina ixtahuacan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'santa lucia utatlan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'san andres semetabaj');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'concepcion');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'san jose chacaya');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'panajachel');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'santa cruz la laguna');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'san marcos la laguna');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'san pablo la laguna');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'santa clara la laguna');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'santa catarina palapo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'santa maria visitacion');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'san juan la laguna');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'san antonio palapo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'san pedro la laguna');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'santiago atitlan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (19,'san lucas toliman');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'pueblo nuevo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'san francisco zapotitlan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'zunilito');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'chicacao');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'santo tomas la union');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'san pablo jocopila');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'cuyotenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'samayac');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'mazatenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'santa barbara');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'san antonio suchitepequez');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'patulul');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'san bernandino');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'san miguel panan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'san gabriel');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'santo domingo suchitepequez');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'san lorenzo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'san jose el idolo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'rio bravo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (20,'san juan bautista');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (21,'momostenango');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (21,'santa lucia la reforma');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (21,'san bartolo aguas calientes');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (21,'santa maria chiquimula');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (21,'san francisco el alto');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (21,'san cristobal totonicapan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (21,'totonicapan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (21,'san andres xecul');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (22,'gualan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (22,'rio hondo');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (22,'teculutan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (22,'zacapa');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (22,'usumatlan');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (22,'estanzuela');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (22,'la union');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (22,'huite');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (22,'cabañas');
INSERT INTO `municipio`(`departamento_id`,`nombre`) VALUES (22,'san diego');