<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4" style="text-align:center;">
        <div class="form-group">
            <div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="mantener_pagina_checkbox"> Quedarse en esta ventana despues de la creacion
                    </label>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4"></div>
</div>