<div class="row">
    <div class="col-md-12">
        <form role="form" id="departamento_form">
            <input type="hidden" class="form-control" id="departamento_id" name="departamento_id">
            <div class="form-group">
                <label>Pais</label>
                <select class="form-control" id="pais_id" name="pais_id">
                    <option value="">selecciona un pais</option>
                </select>
                <label>Nombre</label>
                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
            </div>
        </form>
    </div>
</div>