<div class="row">
    <div class="alert alert-danger" id="error-alert" style="display:none;"></div>
    <div class="alert alert-success" id="success-alert" style="display:none;">
        <strong>El departamento se ha creado con exito.</strong>
    </div>
</div>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <?php echo $this->formulario; ?>
    </div>
    <div class="col-md-4"></div>
</div>
<div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2" style="text-align:center;">
        <button type="button" class="btn btn-primary" onClick="guardar();">Guardar Departamento</button>
    </div>
    <div class="col-md-5"></div>
</div>
<?php
$this->headScript()->appendFile('/js/departamento/formulario.js');
$this->headScript()->appendFile('/js/departamento/nuevo.js');
?>