<div class="row">
    <div class="col-md-12">
        <form role="form" id="guia_form">
            <input type="hidden" class="form-control" id="guia_id" name="guia_id">
            <div class="form-group">
                <label>Cliente</label>
                <select class="form-control" id="cliente_id" name="cliente_id">
                    <option value="">selecciona un cliente</option>
                </select>
                <label>Categoria</label>
                <select class="form-control" id="categoria_id" name="categoria_id">
                    <option value="">selecciona una categoria</option>
                </select>
            </div>
        </form>
    </div>
</div>