<tr>
    <td><?php echo $this->guia->getCliente()->getPrimerNombre(); ?></td>
    <td><?php echo $this->guia->getCliente()->getPrimerApellido(); ?></td>
    <td><?php echo $this->guia->getCategoria()->getNombre(); ?></td>
    <td>
        <button type="button" class="btn btn-sm btn-default" onClick="edit(<?php echo $this->guia->getId(); ?>);">
            <span class="glyphicon glyphicon-edit"></span>
        </button>
        <button type="button" class="btn btn-sm btn-danger" onClick="borrar(<?php echo $this->guia->getId(); ?>);">
            <span class="glyphicon glyphicon-remove"></span>
        </button>
    </td>
</tr>