<div class="col-md-12">
    <form role="form" id="logro_form">
        <input type="hidden" class="form-control" id="logro_id" name="logro_id">
        <div class="form-group">
            <label>Nombre</label>
            <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
            <label>Pais</label>
            <select class="form-control" id="actividad_id" name="actividad_id">
                <option value="">selecciona una actividad</option>
                <?php echo $this->actividades; ?>
            </select>
        </div>
    </form>
</div>
