<div class="row">
    <form role="form" id="logro_form">
        <div class="col-md-6">
            <input type="hidden" class="form-control" id="logro_id" name="logro_id">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
            </div>

        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>Se puede obtener completando las actividades</label>
                <div id="actividades">
                    <?php echo $this->actividades; ?>
                </div>
            </div>
        </div>
    </form>
</div>