<div class="row">
    <div class="col-md-12">
        <form role="form" id="logro_form">
            <input type="hidden" class="form-control" id="logro_id" name="logro_id">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
            </div>
        </form>
    </div>
</div>